package com.scorchedphoto.app.terrainpreview

import android.content.pm.ActivityInfo
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.gestures.awaitEachGesture
import androidx.compose.foundation.gestures.awaitFirstDown
import androidx.compose.foundation.gestures.drag
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.unit.IntSize
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.scorchedphoto.app.ui.LockScreenOrientation
import com.scorchedphoto.terrain.HeightMap
import kotlin.math.roundToInt

@Composable
fun TerrainPreviewScreen(
    onAccept: () -> Unit,
    onRetake: () -> Unit,
    viewModel: TerrainPreviewViewModel = hiltViewModel(),
) {
    LockScreenOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE)
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    Scaffold { padding ->
        Box(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding),
        ) {
            val photo = uiState.photo
            val heightMap = uiState.heightMap

            if (photo != null) {
                val imageBitmap = remember(photo) { photo.asImageBitmap() }
                val drawModifier = if (uiState.isDrawingMode && heightMap != null) {
                    Modifier.terrainDrawGestures(heightMap, onPaint = viewModel::paintColumns)
                } else {
                    Modifier
                }
                Canvas(modifier = Modifier.fillMaxSize().then(drawModifier)) {
                    drawImage(
                        image = imageBitmap,
                        dstSize = IntSize(size.width.roundToInt(), size.height.roundToInt()),
                    )
                    if (heightMap != null) {
                        val scaleX = size.width / heightMap.width
                        val scaleY = size.height / heightMap.height
                        val path = Path()
                        heightMap.groundY.forEachIndexed { x, y ->
                            val px = x * scaleX
                            val py = y * scaleY
                            if (x == 0) path.moveTo(px, py) else path.lineTo(px, py)
                        }
                        val strokeColor = if (uiState.isDrawingMode) Color(0xFF00E5FF) else Color(0xFFFFC107)
                        drawPath(path, color = strokeColor, style = Stroke(width = 4f))
                    }
                }
            }

            if (uiState.isLoading) {
                CircularProgressIndicator(modifier = Modifier.align(Alignment.Center))
            }

            if (uiState.isDrawingMode) {
                Text(
                    "Drag to draw the ground",
                    color = Color.White,
                    modifier = Modifier
                        .align(Alignment.TopCenter)
                        .padding(top = 16.dp),
                )
            }

            Column(
                modifier = Modifier
                    .align(Alignment.BottomCenter)
                    .padding(24.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
            ) {
                Button(onClick = onAccept, enabled = heightMap != null) {
                    Text("Play")
                }
                Row(modifier = Modifier.padding(top = 12.dp)) {
                    Button(onClick = onRetake) {
                        Text("Retake")
                    }
                    if (uiState.isDrawingMode) {
                        Button(
                            onClick = viewModel::clearDrawing,
                            modifier = Modifier.padding(start = 8.dp),
                        ) {
                            Text("Clear")
                        }
                        Button(
                            onClick = viewModel::useAutoGenerated,
                            modifier = Modifier.padding(start = 8.dp),
                        ) {
                            Text("Use Photo Terrain")
                        }
                    } else {
                        Button(
                            onClick = viewModel::regenerate,
                            modifier = Modifier.padding(start = 8.dp),
                            enabled = !uiState.isLoading,
                        ) {
                            Text("Regenerate")
                        }
                        Button(
                            onClick = viewModel::startDrawing,
                            modifier = Modifier.padding(start = 8.dp),
                            enabled = heightMap != null,
                        ) {
                            Text("Draw Your Own")
                        }
                    }
                }
            }
        }
    }
}

/**
 * Drag-to-paint gesture for hand-drawing terrain: on each touch, converts screen-space
 * pointer positions into (column, row) coordinates in [heightMap]'s pixel space (inverting
 * the same scale math the Canvas above uses to render the overlay line), then reports
 * [onPaint] calls the ViewModel forwards straight into [TerrainPreviewViewModel.paintColumns].
 * Uses awaitFirstDown()/drag() rather than detectDragGestures() so a deliberate single tap
 * (no drag) still paints that one column, matching the same reasoning as AngleRing's gesture.
 */
private fun Modifier.terrainDrawGestures(
    heightMap: HeightMap,
    onPaint: (fromColumn: Int?, fromRow: Int, toColumn: Int, toRow: Int) -> Unit,
): Modifier = pointerInput(heightMap.width, heightMap.height) {
    fun Offset.toColumnRow(): Pair<Int, Int> {
        val scaleX = size.width.toFloat() / heightMap.width
        val scaleY = size.height.toFloat() / heightMap.height
        val column = (x / scaleX).roundToInt().coerceIn(0, heightMap.width - 1)
        val row = (y / scaleY).roundToInt().coerceIn(0, heightMap.height - 1)
        return column to row
    }
    awaitEachGesture {
        val down = awaitFirstDown()
        down.consume()
        val (startColumn, startRow) = down.position.toColumnRow()
        onPaint(null, startRow, startColumn, startRow)
        var lastColumn = startColumn
        var lastRow = startRow
        drag(down.id) { change ->
            change.consume()
            val (column, row) = change.position.toColumnRow()
            onPaint(lastColumn, lastRow, column, row)
            lastColumn = column
            lastRow = row
        }
    }
}
