package com.scorchedphoto.app.terrainpreview

import android.graphics.Bitmap
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.scorchedphoto.app.capture.ImageDownscaler
import com.scorchedphoto.app.capture.PhotoRepository
import com.scorchedphoto.app.ml.FallbackSkySignalProvider
import com.scorchedphoto.terrain.HeightMap
import com.scorchedphoto.terrain.TerrainSegmentationStyle
import com.scorchedphoto.terrain.TerrainSegmenter
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject
import kotlin.math.max
import kotlin.math.min
import kotlin.math.roundToInt
import kotlin.random.Random

// Mirrors TerrainSegmenter's sky-headroom clamp and CraterCarver's max-dig-depth clamp
// (both private to :terrain/:engine) so hand-drawn terrain can't produce a degenerate
// shape - e.g. a spike touching the sky ceiling, or ground with no depth to carve into.
private const val MIN_HEIGHT_FRACTION = 0.08f
private const val MAX_HEIGHT_FRACTION = 0.95f
private const val FLAT_BASELINE_FRACTION = 0.6f

data class TerrainPreviewUiState(
    val photo: Bitmap? = null,
    val heightMap: HeightMap? = null,
    val isLoading: Boolean = true,
    val isDrawingMode: Boolean = false,
)

@HiltViewModel
class TerrainPreviewViewModel @Inject constructor(
    private val photoRepository: PhotoRepository,
    private val terrainRepository: TerrainRepository,
    private val skySignalProvider: FallbackSkySignalProvider,
) : ViewModel() {

    private val _uiState = MutableStateFlow(TerrainPreviewUiState())
    val uiState: StateFlow<TerrainPreviewUiState> = _uiState.asStateFlow()

    private var segmentJob: Job? = null

    // The last photo-derived terrain, and the user's in-progress hand-drawn terrain (if
    // any) - kept separately so toggling between "Draw Your Own" and "Use Photo Terrain"
    // never discards either one. Neither is exposed directly; uiState.heightMap always
    // reflects whichever is currently active.
    private var autoGeneratedHeightMap: HeightMap? = null
    private var drawnHeightMap: HeightMap? = null

    init {
        segment(seed = System.nanoTime())
    }

    fun regenerate() {
        segment(seed = System.nanoTime())
    }

    /** Switches into draw mode, seeding the drawing from a copy of the current
     * photo-derived terrain the first time (or resuming a prior in-progress drawing). */
    fun startDrawing() {
        val active = drawnHeightMap
            ?: autoGeneratedHeightMap?.let { HeightMap(it.width, it.height, it.groundY.copyOf()) }
            ?: return
        drawnHeightMap = active
        setActive(active, isDrawingMode = true)
    }

    /** Resets the in-progress drawing to a flat baseline, staying in draw mode. */
    fun clearDrawing() {
        val reference = autoGeneratedHeightMap ?: drawnHeightMap ?: return
        val flat = flatHeightMap(reference)
        drawnHeightMap = flat
        setActive(flat, isDrawingMode = true)
    }

    /** Leaves draw mode, restoring the last photo-derived terrain as active. */
    fun useAutoGenerated() {
        val auto = autoGeneratedHeightMap ?: return
        setActive(auto, isDrawingMode = false)
    }

    /**
     * Paints columns [fromColumn]..[toColumn] (inclusive, either order) into the active
     * drawing, linearly interpolating row values between the two samples so a fast drag
     * that skips columns between two pointer-move events still draws a continuous line.
     * Pass [fromColumn] = null to paint a single column ([toColumn], [toRow]) only - used
     * for the first sample of a new touch, so starting a fresh stroke elsewhere never
     * draws a line back to wherever a previous, separate stroke ended.
     */
    fun paintColumns(fromColumn: Int?, fromRow: Int, toColumn: Int, toRow: Int) {
        val current = drawnHeightMap ?: return
        val startColumn = fromColumn ?: toColumn
        val startRow = if (fromColumn == null) toRow else fromRow
        val newGroundY = current.groundY.copyOf()
        val minCol = min(startColumn, toColumn)
        val maxCol = max(startColumn, toColumn)
        val span = toColumn - startColumn
        for (col in minCol..maxCol) {
            val t = if (span == 0) 0f else (col - startColumn).toFloat() / span
            newGroundY[col] = clampRow((startRow + t * (toRow - startRow)).roundToInt(), current.height)
        }
        val updated = HeightMap(current.width, current.height, newGroundY)
        drawnHeightMap = updated
        setActive(updated, isDrawingMode = true)
    }

    /** Writes [heightMap] through to both the repository (so Play, which reads it
     * directly, always sees the latest terrain) and uiState (for the screen to render). */
    private fun setActive(heightMap: HeightMap, isDrawingMode: Boolean) {
        terrainRepository.heightMap = heightMap
        _uiState.value = _uiState.value.copy(heightMap = heightMap, isDrawingMode = isDrawingMode)
    }

    private fun flatHeightMap(reference: HeightMap): HeightMap {
        val flatRow = clampRow((reference.height * FLAT_BASELINE_FRACTION).roundToInt(), reference.height)
        return HeightMap(reference.width, reference.height, IntArray(reference.width) { flatRow })
    }

    private fun clampRow(row: Int, heightMapHeight: Int): Int {
        val minRow = (heightMapHeight * MIN_HEIGHT_FRACTION).roundToInt()
        val maxRow = (heightMapHeight * MAX_HEIGHT_FRACTION).roundToInt()
        return row.coerceIn(minRow, maxRow)
    }

    private fun segment(seed: Long) {
        val photo = photoRepository.workingPhoto ?: return
        segmentJob?.cancel()
        // A fresh photo/segmentation invalidates any in-progress hand-drawn terrain from
        // a previous session, since it was shaped against the old terrain as a starting
        // point - resurrecting it here would silently show stale, unrelated work.
        drawnHeightMap = null
        _uiState.value = TerrainPreviewUiState(photo = photo, heightMap = null, isLoading = true)
        segmentJob = viewModelScope.launch(Dispatchers.Default) {
            val pixelBuffer = ImageDownscaler.toPixelBuffer(photo)
            // Reuses this same per-tap seed to vary the seam search's "shape" style too,
            // not just the (rare) all-sky fallback path - otherwise Regenerate is a no-op
            // for any photo with a real, detectable ground/sky boundary.
            val style = TerrainSegmentationStyle.random(Random(seed))
            val heightMap = TerrainSegmenter.segment(pixelBuffer, seed, skySignalProvider, style)
            autoGeneratedHeightMap = heightMap
            terrainRepository.heightMap = heightMap
            _uiState.value = TerrainPreviewUiState(photo = photo, heightMap = heightMap, isLoading = false)
        }
    }
}
